### ISSUE TITLE
No binary for 2.2.0

### ISSUE THREAD

**Issue by linsui** [andipabst/vergiss-nix#5]
F-Droid needs to download the apk signed by you to get the signature.

**Comment by andipabst** [comment]
Thanks for the reminder, binary is added now.

**Comment by linsui** [comment]
Could you change the file name to vergiss-nix-2.2.0.apk as previous versions?

**Comment by andipabst** [comment]
Done. Sorry, I totally forgot about the process.

**Comment by linsui** [comment]
Thanks!
